{
 "title": "医疗健康",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "总支出",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  counterparty AS '机构名称',\r\n  amount AS '支出费用'\r\nFROM\r\n  transaction\r\nWHERE\r\n  category = '医疗健康'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp ASC"
    }
   ]
  },
  {
   "title": "支出明细",
   "type": "table",
   "gridPos": { "h": 16, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  timestamp AS '发生时间',\r\n  counterparty AS '机构名称',\r\n  amount AS '支出费用'\r\nFROM\r\n  transaction\r\nWHERE\r\n  category = '医疗健康'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp DESC"
    }
   ]
  },
  {
   "title": "\"免费\"次数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  counterparty AS '机构名称',\r\n  amount AS '支出费用'\r\nFROM\r\n  transaction\r\nWHERE\r\n  category = '医疗健康'\r\n  AND amount = 0\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp ASC"
    }
   ]
  }
 ]
}