{
 "title": "我的支出情况",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "总支出",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  amount\r\nFROM\r\n  dashboard.transaction\r\nWHERE\r\n  income_or_expenditure = '支出'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp ASC"
    }
   ]
  },
  {
   "title": "月度支出",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  DATE_FORMAT(timestamp, '%Y-%m') AS month,\r\n  SUM(amount) AS '总支出'\r\nFROM\r\n  dashboard.transaction\r\nWHERE\r\n  income_or_expenditure = '支出'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n  DATE_FORMAT(timestamp, '%Y-%m')\r\nORDER BY\r\n  month ASC"
    }
   ]
  },
  {
   "title": "分层支出",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    CASE\r\n        WHEN amount BETWEEN 0 AND 9.99 THEN '0-9'\r\n        WHEN amount BETWEEN 10 AND 49.99 THEN '10-49'\r\n        WHEN amount BETWEEN 50 AND 99.99 THEN '50-99'\r\n        WHEN amount BETWEEN 100 AND 199.99 THEN '100-199'\r\n        WHEN amount BETWEEN 200 AND 499.99 THEN '200-499'\r\n        WHEN amount BETWEEN 500 AND 999.99 THEN '500-999'\r\n        WHEN amount BETWEEN 1000 AND 2999.99 THEN '1000-2999'\r\n        ELSE '3000+'\r\n    END AS amount_range,\r\n    COUNT(*) AS '总笔数'\r\nFROM\r\n    dashboard.transaction\r\nWHERE\r\n  income_or_expenditure = '支出'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    amount_range\r\nORDER BY\r\n    MIN(amount)"
    }
   ]
  },
  {
   "title": "大额支出",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  timestamp AS '交易时间',\r\n  category AS '订单分类',\r\n  counterparty AS '商户名称',\r\n  amount AS '消费金额'\r\nFROM\r\n  dashboard.transaction\r\nWHERE\r\n  income_or_expenditure = '支出'\r\n  AND amount > 499.99\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp DESC"
    }
   ]
  },
  {
   "title": "信用借还",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  timestamp,\r\n  counterparty AS '卡商',\r\n  goods AS '还款类目',\r\n  amount AS '实还本息'\r\nFROM\r\n  dashboard.transaction\r\nWHERE\r\n  category = '信用借还'\r\n  AND counterparty = '广发银行'\r\n  AND income_or_expenditure = '不计收支'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp ASC"
    }
   ]
  },
  {
   "title": "支出趋势",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  timestamp,\r\n  amount AS '支出金额'\r\nFROM\r\n  dashboard.transaction\r\nWHERE\r\n  income_or_expenditure = '支出'\r\n  AND timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  timestamp ASC"
    }
   ]
  }
 ]
}