{
 "title": "消费习惯",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  { "title": "命苦吃快餐", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "总共吃了多少顿快餐",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  DATE_FORMAT(timestamp, '%Y-%m') AS month,\r\n  COUNT(t.counterparty) AS '订单数'\r\nFROM \r\n    transaction t\r\nJOIN \r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE \r\n    tt.tag LIKE '%快餐%'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n  DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n  month ASC"
    }
   ]
  },
  {
   "title": "都在哪家吃 & 花了多少钱",
   "type": "table",
   "gridPos": { "h": 16, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '消费金额'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "快餐价位趋势（早/中/晚）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '早餐'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND HOUR(t.timestamp) BETWEEN 5 AND 10\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '中餐'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND HOUR(t.timestamp) BETWEEN 11 AND 15\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '晚餐'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND HOUR(t.timestamp) BETWEEN 16 AND 20\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '夜宵'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND HOUR(t.timestamp) BETWEEN 21 AND 23\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '大半夜呢?'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag LIKE '%快餐%'\r\n  AND HOUR(t.timestamp) BETWEEN 0 AND 4\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  { "title": "线上逛超市", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "总共花了多少钱",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  DATE_FORMAT(t.timestamp, '%Y-%m') AS month,\r\n  SUM(t.amount) AS '总金额'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag = '朴朴'\r\n  AND tt.field = 'counterparty'\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n  DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n  month ASC"
    }
   ]
  },
  {
   "title": "都在哪家买 & 花了多少钱",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 18 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '商户名称',\r\n  t.amount AS '消费金额'\r\nFROM\r\n  transaction t\r\n  JOIN transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag = '朴朴'\r\n  AND tt.field = 'counterparty'\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  { "title": "咖啡大师", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "买了多少杯咖啡(订单数)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    COUNT(t.counterparty) AS '订单数'\r\nFROM \r\n    transaction t\r\nJOIN \r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE \r\n    tt.tag LIKE '%咖啡%'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())"
    }
   ]
  },
  {
   "title": "买了多少钱的咖啡",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT \r\n    SUM(t.amount) AS '总消费金额'\r\nFROM \r\n    transaction t\r\nJOIN \r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE \r\n    tt.tag LIKE '%咖啡%'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())"
    }
   ]
  },
  {
   "title": "贡献了多少钱给瑞幸",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT \r\n    SUM(t.amount) AS '总消费金额'\r\nFROM \r\n    transaction t\r\nJOIN \r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE \r\n    tt.tag = '瑞幸咖啡'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())"
    }
   ]
  },
  { "title": "生活缴费", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "水费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '水费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "水费（月支出）",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 36 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '水费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "水费（缴费记录）",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 36 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    t.timestamp AS '缴费时间',\r\n    t.counterparty AS '缴费机构',\r\n    t.amount AS '金额'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '水费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "电费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '电费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "电费（月支出）",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 44 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '电费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "电费（缴费记录）",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 44 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    t.timestamp AS '缴费时间',\r\n    t.counterparty AS '缴费机构',\r\n    t.amount AS '金额'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '电费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "燃气费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '燃气费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "燃气费（月支出）",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 52 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '燃气费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "燃气费（缴费记录）",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 52 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    t.timestamp AS '缴费时间',\r\n    t.counterparty AS '缴费机构',\r\n    t.amount AS '金额'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '燃气费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "网费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '宽带'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "网费（月支出）",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 60 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '宽带'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "网费（缴费记录）",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 60 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    t.timestamp AS '缴费时间',\r\n    t.counterparty AS '缴费机构',\r\n    t.amount AS '金额'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '宽带'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "话费",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '话费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "话费（月支出）",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 68 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    DATE_FORMAT(t.timestamp, '%Y-%m') AS '年-月',\r\n    SUM(t.amount) AS '月支出'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '话费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nGROUP BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')\r\nORDER BY\r\n    DATE_FORMAT(t.timestamp, '%Y-%m')"
    }
   ]
  },
  {
   "title": "话费（缴费记录）",
   "type": "table",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 68 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n    t.timestamp AS '缴费时间',\r\n    t.counterparty AS '缴费机构',\r\n    t.amount AS '金额'\r\nFROM\r\n    transaction t\r\nJOIN\r\n    transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n    tt.tag = '话费'\r\n    AND tt.field = 'counterparty'\r\n    AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  { "title": "租房费用", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 } },
  {
   "title": "总支出",
   "type": "stat",
   "gridPos": { "h": 13, "w": 10, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '机构名称',\r\n  t.amount AS '支付金额'\r\nFROM\r\n  dashboard.transaction t\r\n  JOIN dashboard.transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag = '租房'\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  },
  {
   "title": "总支出",
   "type": "table",
   "gridPos": { "h": 13, "w": 14, "x": 10, "y": 77 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  t.timestamp AS '交易时间',\r\n  t.category AS '订单分类',\r\n  t.counterparty AS '机构名称',\r\n  t.amount AS '支付金额'\r\nFROM\r\n  dashboard.transaction t\r\n  JOIN dashboard.transaction_tag tt ON t.counterparty = tt.value\r\nWHERE\r\n  tt.tag = '租房'\r\n  AND t.timestamp BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  t.timestamp DESC"
    }
   ]
  }
 ]
}