# Dashboard Stack

networks:
  dashboard-network:
    name: ${NETWORK_NAME}
    driver: bridge

volumes:
  mysql-data:
  grafana-data:

services:

  # MySQL
  # https://dev.mysql.com/doc/refman/8.4/en/
  mysql:
    image: ${REGISTRY:-docker.io}/${MYSQL_IMAGE:-mysql:latest}
    container_name: mysql
    hostname: mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:?root password is required}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-dashboard}
      MYSQL_USER: ${MYSQL_USER:-dashboard}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:?password is required}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dashboard-network
    profiles:
      - all
      - base
      - database
      - mysql
    healthcheck:
      test: ["CMD", "sh", "-c", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD 2>/dev/null | grep -q alive"]
      interval: 30s
      timeout: 10s
      retries: 3

  phpmyadmin:
    image: ${REGISTRY:-docker.io}/${PMA_IMAGE:-phpmyadmin/phpmyadmin:latest}
    container_name: phpmyadmin
    hostname: phpmyadmin
    restart: unless-stopped
    ports:
      - ${PMA_PORT:-80}:80
    environment:
      PMA_ARBITRARY: ${PMA_ARBITRARY:-1}
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - dashboard-network
    depends_on:
      - mysql
    profiles:
      - all
      - base
      - database
      - mysql
      - phpmyadmin

  # Grafana
  # https://grafana.com/docs/grafana/latest/
  grafana:
    image: ${REGISTRY:-docker.io}/${GRAFANA_IMAGE:-grafana/grafana:latest}
    container_name: grafana
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USERNAME:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:?"Environment variable GRAFANA_ADMIN_PASSWORD is required"}
      GF_USERS_ALLOW_SIGN_UP: "false"
      GRAFANA_MYSQL_PASSWORD: ${MYSQL_PASSWORD:?password is required}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/provisioning/dashboards/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - dashboard-network
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/robots.txt"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - all
      - dashboard
      - grafana
