{
 "title": "我的收入情况",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "税后总收入",
   "type": "stat",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  amount\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    }
   ]
  },
  {
   "title": "月收入",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '工资'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '工资'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    }
   ]
  },
  {
   "title": "其他收入",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '年终奖'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '年终奖'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '裁员赔偿'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '裁员赔偿'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '补贴'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '补贴'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '奖金'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '奖金'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    },
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  dtm,\r\n  amount AS '其他'\r\nFROM\r\n  dashboard.salary\r\nWHERE\r\n  category = '其他'\r\n  AND dtm BETWEEN FROM_UNIXTIME($__unixEpochFrom()) AND FROM_UNIXTIME($__unixEpochTo())\r\nORDER BY\r\n  dtm ASC"
    }
   ]
  }
 ]
}