{
 "title": "房贷还款",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "已还本息总额",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  SUM(actual_principal_interest) AS '已还本息总额'\r\nFROM\r\n  dashboard.loan"
    }
   ]
  },
  {
   "title": "提前还款记录",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  actual_interest_payment_date AS '实际还款时间',\r\n  actual_principal AS '实还本金',\r\n  actual_interest AS '实还利息'\r\nFROM\r\n  dashboard.loan\r\nWHERE\r\n  period > 1000\r\nORDER BY\r\n  actual_interest_payment_date DESC"
    }
   ]
  },
  {
   "title": "实还本金&利息",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dashboard",
     "rawSql": "SELECT\r\n  actual_interest_payment_date AS '实际还款时间',\r\n  actual_principal AS '实还本金',\r\n  actual_interest AS '实还利息'\r\nFROM\r\n  dashboard.loan\r\nWHERE\r\n  actual_principal_interest < 20000\r\nORDER BY\r\n  actual_interest_payment_date ASC"
    }
   ]
  }
 ]
}